// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentPlanner.Data;

#nullable disable

namespace SacramentPlanner.Migrations
{
    [DbContext(typeof(SacramentPlannerContext))]
    partial class SacramentPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("SacramentPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("closingHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("closingPrayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("conductor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("openingHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("openingPrayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("restHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("sacramentHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("speakerNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("specialMusicalNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("wardName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
